### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by prateekbh**
- adds missing tabs packages
- better perf for docs

P.S. review after changesFor39 are in

### CODE REVIEW

**Comment by artipost** [comment]
Failed pictures (5): [failed-pictures.zip]

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [431727661](https://travis-ci.org/prateekbh/preact-material-components/builds/431727661), for commit [c236600](https://github.com/prateekbh/preact-material-components/pull/1007/commits/c2366008770cd441e22c13971d8a191dab33e5a8).

**Comment by cromefire** [comment]
Looks good so far

**Comment by artipost** [comment]
Failed pictures (2): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/b1739adc975320488af925ca59923489/raw/e040d87c48ae208facd86bbaa29d26ebbdd00b97/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [431925027](https://travis-ci.org/prateekbh/preact-material-components/builds/431925027), for commit [b1c7049](https://github.com/prateekbh/preact-material-components/pull/1007/commits/b1c704953c53de2dbf6387fc481f534dc36d0b46).

**Comment by prateekbh** [comment]
@cromefire ready for review

**Pull request merged**
