### PR TITLE
Fixing33

### PR DESCRIPTION
**Pull request by prateekbh**
- removes button's compact version
- adds image-list
-fixes chips
- adds chips checkmark

### CODE REVIEW

**Comment by artipost** [comment]
Failed pictures (133): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/2a4654c07a53da0643f08090b1e5af1f/raw/c6012a3e635a758a7a9577bec863fd8471a515d7/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [358615135](https://travis-ci.org/prateekbh/preact-material-components/builds/358615135), for commit [cdae4cf](https://github.com/prateekbh/preact-material-components/pull/700/commits/cdae4cfb3a27a218601f32accc95cfbe934696f2).

**Comment by filoozom** [comment]
Go home @artipost, you're drunk. I'll have to fix that. Strange that it only happened now?

**Comment by artipost** [comment]
Failed pictures (3): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/2aa6b2fece6e80f57510581d1e4b3b71/raw/20096f40f461fc754770511eac233f7a51abfef3/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [358618811](https://travis-ci.org/prateekbh/preact-material-components/builds/358618811), for commit [4bf00db](https://github.com/prateekbh/preact-material-components/pull/700/commits/4bf00db876663c78a1fe55849b4c00f47bc91997).

**Comment by prateekbh** [comment]
Will wait for a day or two more if I can get a review done

**Pull request merged**
