### PR TITLE
doc: Adding textfield demo code

### PR DESCRIPTION
**Pull request by wuweiweiwu**
#264

### CODE REVIEW

**Comment by prateekbh** [comment]
@filoozom this should've failed: https://travis-ci.org/prateekbh/preact-material-components/jobs/349522532

**Comment by prateekbh** [comment]
@wuweiweiwu lol, i am expecting this to fail beacause this should've been caught by our visual diff testing. But it seems they didn't even ran

**Comment by wuweiweiwu** [comment]
@prateekbh I was wondering if there was a day to run the visual diff locally but it seems like the image heights depend on your computer's resolution?

**Comment by prateekbh** [comment]
+ your screen resolution etc etc... i'll found the bug i guess. will fix it on my way to home

**Comment by prateekbh** [comment]
or in case if you wanna try out... 
I guess we dont need this code any more: https://github.com/prateekbh/preact-material-components/blob/master/scripts/travis.sh#L22-L54

as we need to run test fr everything now.

**Comment by wuweiweiwu** [comment]
@prateekbh Should those lines just be deleted?

**Comment by prateekbh** [comment]
yeah i guess they should just be deleted. also no `page.setViewport()` wont work tried and failed

**Comment by wuweiweiwu** [comment]
@prateekbh I still get test failures because of the image diffing tests. Should I just ignore them?

**Comment by prateekbh** [comment]
@wuweiweiwu here I fixed it for you. You are expected to get this failure. 
See the log for the `file.io` link. download the zip and replace the failing page screenshot in the `golden` dir.


screen shot 2018-03-06 at 2 48 01 pm

**Comment by prateekbh** [comment]
Thank you @wuweiweiwu and sorry for the pain, this was indeed our 1st PR after we set up our tests.

**Comment by prateekbh** [comment]
And its live!

**Comment by wuweiweiwu** [comment]
No problem! 🎉

**Pull request merged**
