### PR TITLE
Update IconButton

### PR DESCRIPTION
**Pull request by prateekbh**

### CODE REVIEW

**Comment by cromefire** [comment]
Could you please verify the `eyes` report and rerun the tests? I'm currently not on a desktop.

**Comment by cromefire** [comment]
Also the whole build is failing

**Comment by prateekbh** [comment]
Thanks.. was away for a week for vacation 😄

**Comment by cromefire** [comment]
```
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

cypress/integration/visual-test/icon-button-test.spec.js
```

**Pull request merged**
