### PR TITLE
updating documentation

### PR DESCRIPTION
**Pull request by prateekbh**
updating documentation for 1.1.6

### CODE REVIEW

**Comment by prateekbh** [comment]
also , I need to check how to remove travis from this branch

**Comment by filoozom** [comment]
I'll be doing some work on Travis for the documentation update to ```preact-cli```, will have a look at the same time.

**Comment by prateekbh** [comment]
will do

**Comment by prateekbh** [comment]
done

**Comment by prateekbh** [comment]
I guess we'll need to force submit this one

**Comment by filoozom** [comment]
Yes, tried to re-run the build to see if it would just ignore the build and accept it, but it didn't want to. Could also just add a commit, should do the trick I think.

**Comment by prateekbh** [comment]
about package.json, i dont really have a strong opinion, but yeah i guess I should make peace with it... will add it in next pushes

**Comment by filoozom** [comment]
Wait, why did you add ```espree``` and ```babel-generator```?

**Comment by prateekbh** [comment]
`babel-generator` was due to the error being thrown and espree also i guess was a sub dependency

**Pull request merged**
