### PR TITLE
Improved TextField validation - TS version

### PR DESCRIPTION
**Pull request by cromefire**
The new version of #873 for the new ts build system.

### CODE REVIEW

**Comment by cromefire** [comment]
Accidentally branched of from the the other PR.

**Comment by artipost** [comment]
Failed pictures (27): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/c8935d0e3bd3b8f0f931d509aa5ac798/raw/c04df81951cde92250e764650d3ea125ebbe8827/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [413504922](https://travis-ci.org/prateekbh/preact-material-components/builds/413504922), for commit [6f7c8eb](https://github.com/prateekbh/preact-material-components/pull/921/commits/6f7c8eb47ed8c8e66707b9e7a6da914a9a0b6468).

**Comment by prateekbh** [comment]
i guess we had the same conversation earlier that this should be done by app code and `ref.MDComponent.valid` should be set by app code then.

**Comment by cromefire** [comment]
You requested other ones to have a look, because you were not sure that was the last thing. See #873.

**Comment by cromefire** [comment]
Need remake in `2.0`

**Comment by cromefire** [comment]
Leave branch please

**Pull request closed without merging**
