### PR TITLE
Ripple component

### PR DESCRIPTION
**Pull request by cromefire**
Ripple component that just attaches a ripple to something

### CODE REVIEW

**Comment by cromefire** [comment]
@prateekbh do you know why the component doesn't work? I'm pretty sure I got every thing right

**Comment by prateekbh** [comment]
how come this PR is not getting a netlify preview

**Comment by cromefire** [comment]
I don't know, maybe I need to push after it's not WIP

**Comment by prateekbh** [comment]
I see that the javascript is working fine... i guess styling is a problem:

https://github.com/material-components/material-components-web/tree/master/packages/mdc-ripple#sass-apis

**Comment by cromefire** [comment]
That may indeed be the case

**Comment by cromefire** [comment]
Fixed, review pls

**Comment by prateekbh** [comment]
the preview doesnt seem to work :/

**Comment by cromefire** [comment]
That's correct but in the preview a bunch of things do not work (e.g. the switch)

**Comment by prateekbh** [comment]
WDYM? isnt the switch page working?

**Comment by cromefire** [comment]
The one for dark mode. You can toggle it, dark mode works, but the switch _looks_ like it's off

**Comment by prateekbh** [comment]
Screen Shot 2019-08-01 at 3 16 18 PM

Off as in?

**Comment by cromefire** [comment]
This is how it looks to me (FF 68):
image

**Comment by cromefire** [comment]
It's some how just missing css rules (and I don't know why, no errors on console, no failed network requests)

**Comment by prateekbh** [comment]
lol at least it works in chrome...
anyways can you just add a dummy test and then we can merge it if this works for you

**Comment by cromefire** [comment]
> lol at least it works in chrome...

It's also working locally for me

**Comment by prateekbh** [comment]
I'll be able to PR tabs only after 7th Aug, feel free to take it if you want

**Comment by cromefire** [comment]
Will look at it if I've got some time

**Pull request merged**
