### PR TITLE
[WIP] Post comment containing failed pictures to PR

### PR DESCRIPTION
**Pull request by filoozom**
The goal of this bot is to make it easier to update visual diff pictures created in #624 and #626.

- Creates a Gist
- Pushes a zip file to it (can't do it in one step sadly)
- Posts a comment on the failed PR with a link to the zip

The reason why we use Gist is that I don't think that it's currently possible to directly create a comment with files with the GitHub API.

**WIP**: Figure out Travis secrets

### CODE REVIEW

**Comment by filoozom** [comment]
Ok, so this isn't actually doable without an external server I think, so I'll just put this on hold for a bit until I find a solution.

**Comment by developit** [comment]
This would be an awesome dedicated service

**Comment by filoozom** [comment]
Was thinking about that too actually. Do you have any suggestions / whishes? I'm mostly stuck on figuring out the security aspect of it right now.

**Comment by prateekbh** [comment]
so something exactly like percy!

**Comment by filoozom** [comment]
Closing in favour of #668

**Pull request closed without merging**
