### PR TITLE
Improved validation for textfield

### PR DESCRIPTION
**Pull request by cromefire**
- [x] Added docs and definition for 'valid' prop
- [x] Added custom validation functions
- [x] Made sure to not overwrite `onChange` and `onKeyDown` event

### CODE REVIEW

**Comment by artipost** [comment]
Failed pictures (135): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/fa01b7b47be42a424e7602eb9a72f149/raw/9eafd0cc3e8301abf46b452cabf2e8546e85358a/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [406842015](https://travis-ci.org/prateekbh/preact-material-components/builds/406842015), for commit [6619897](https://github.com/prateekbh/preact-material-components/pull/873/commits/661989762cb304108313a5a30aee7f219effd3e0).

**Comment by artipost** [comment]
Failed pictures (135): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/22d7cbba59c11a191d0d959d9b287cec/raw/bcd9fc37238ef222b1bb33c0f9ae79e0ab21aa23/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [406845696](https://travis-ci.org/prateekbh/preact-material-components/builds/406845696), for commit [d1a8e7a](https://github.com/prateekbh/preact-material-components/pull/873/commits/d1a8e7a7a206b63c8c88b330eefef49b6bd869d1).

**Comment by artipost** [comment]
Failed pictures (135): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/26fb9de95c0d8df8c574ec56ce4a665d/raw/4c5363ec707b91d6f5e6ad062c76d631a89cef26/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [406846313](https://travis-ci.org/prateekbh/preact-material-components/builds/406846313), for commit [b62b45b](https://github.com/prateekbh/preact-material-components/pull/873/commits/b62b45b6604d116be8f5200e5e535d342b077e18).

**Comment by cromefire** [comment]
Something with the documentation check is going wrong, something with UglifyJS, please tell me what could cause this

**Comment by prateekbh** [comment]
Why does validation function not be a part of app code instead?

I see a need of `valid` prop and how that directly maps to MDComponent property, but I guess the other two functions should just live in the app code instead. WDYT?

**Comment by cromefire** [comment]
@prateekbh mostly for convenience, I mean the whole library could be implemented in app code, but this is fast and easy to use without much knowledge of the internals.
Else you would have to register an event listener and change the rendering of the component from that listener. That would be 20 lines of code at minimum and wouldn't be very good performance wise.

**Comment by prateekbh** [comment]
hmmm.. i understand but then not everyone would want it as well.
I am super aligned with `valid` prop but not so sure about the functions.

CC: @filoozom @YePpHa @mellogarrett to see if they have any views on this

**Comment by cromefire** [comment]
Further explanation is available in the docs and in the typescript definitions BTW

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/070f52283cb54754d943da20c180fe72/raw/d5be22d110ddccc2e2c0e1d59030f5a543e2de28/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [406904830](https://travis-ci.org/prateekbh/preact-material-components/builds/406904830), for commit [e02e1de](https://github.com/prateekbh/preact-material-components/pull/873/commits/e02e1de4f579fda44880a143028edc974074b027).

**Comment by cromefire** [comment]
Opening a new PR for that, it's faster to redo it that merging this, please don't delete the branch for now.

**Pull request closed without merging**
