### PR TITLE
Improved TypeScript typing for soft merge

### PR DESCRIPTION
**Pull request by cromefire**
See https://github.com/prateekbh/preact-material-components/issues/970#issuecomment-416740564

### CODE REVIEW

**Comment by cromefire** [comment]
Did for that off `mdc-notify` by accident, so has to be merged back there, but shouldn't be that bad because this is not a really big change.

**Comment by prateekbh** [comment]
After this are we good for a stable?

**Comment by cromefire** [comment]
If we can quickly resolve that `MDCTab` thing in the other PR and you don't have anything to complain about I think it is.

**Comment by cromefire** [comment]
> If we can quickly resolve that `MDCTab` thing

Or at least agree on looking at this later again

**Comment by cromefire** [comment]
So if anyone wants to look over this (for example @YePpHa as TS expert), else I'll merge this

**Comment by prateekbh** [comment]
MdcTab thing is not prop friendly as of now... i posted it there and an example.

**Comment by cromefire** [comment]
I just found it in my code completions and I'm not sure, if it should be attached to the tab.
It seems like it should be the case ([see here] (https://material.io/develop/web/components/tabs/tab/))

**Comment by cromefire** [comment]
You know, let me open a PR for this and then we can see

**Comment by cromefire** [comment]
For now as nobody has a complaint, I'll merge this

**Pull request merged**
