### PR TITLE
Updating button

### PR DESCRIPTION
**Pull request by prateekbh**
- Adds icon as a prop to button. (because text is all that can be given to this tag right now)
- adds a wrapper of `.button-label` around the button text

### CODE REVIEW

**Comment by cromefire** [comment]
@prateekbh While we are at `[WIP]`, do you mind to add the WIP bot?

**Comment by cromefire** [comment]
Thanks

**Comment by artipost** [comment]
Failed pictures (2): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/a5b4614cb81fe090199ecd250dfa9d6f/raw/1b0169b5324a070424ba4e9d5f968e038641b8d2/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [488603677](https://travis-ci.org/prateekbh/preact-material-components/builds/488603677), for commit [f7bfd89](https://github.com/prateekbh/preact-material-components/pull/1276/commits/f7bfd8959783cd84f25bb76e6c44a69d79c2aa6c).

**Comment by artipost** [comment]
Failed pictures (2): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/a7d44d1161c484c31d9dc50f0b38b4bf/raw/9b5514503d0173a772ebe5da2418f6e29bb8af1c/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [488607185](https://travis-ci.org/prateekbh/preact-material-components/builds/488607185), for commit [3bb3c00](https://github.com/prateekbh/preact-material-components/pull/1276/commits/3bb3c006ee74b72e9199357737dc5fc538b81966).

**Comment by cromefire** [comment]
Sorry I'm really busy in the next few days

**Comment by prateekbh** [comment]
same.. till 14th feb 👍

**Comment by prateekbh** [comment]
Like what?

**Comment by cromefire** [comment]
I wanted to write a small markdown document

**Comment by prateekbh** [comment]
Like for every component???

Sounds fun. 👍

**Comment by cromefire** [comment]
No one for all, containing things like the file layout of a component (e.g. fesm, ...) or common interfaces

**Comment by prateekbh** [comment]
But why that blocks this PR to be merged 🤔🤔🤔

**Comment by cromefire** [comment]
I want to make sure that we didn't miss anything. it should be irrelevant, whether we merge this now or later or do you need the things from the PR in the main branch?

**Comment by prateekbh** [comment]
Nups, this is just component update for 2.0

**Pull request merged**
