### PR TITLE
Fixed Textfield after mdc upgrade

### PR DESCRIPTION
**Pull request by porfirioribeiro**
After MDC upgrade textfield was renamed to text-field, maybe we should also change Textfield to TextField @prateekbh?

### CODE REVIEW

**Comment by prateekbh** [comment]
Yep we should also change the name of the text field

**Comment by filoozom** [comment]
Actually the folder / file should have been renamed to `TextField` too. I'll change that in the `FormField` PR.

**Comment by filoozom** [comment]
`componentsList.js` is missing the change too for `CssMigrationWebpackPlugin`.

**Comment by prateekbh** [comment]
@filoozom actually i am sending a PR for other changes of 0.25 I guess I can pick this up

**Comment by prateekbh** [comment]
@filoozom moreover the package name hasn't changed so i dont think its needed in `componentsList.js`

**Comment by filoozom** [comment]
@prateekbh I already changed `Textfield` to `TextField` in a PR comming in a few minutes. I'll have a look for the package name.

**Pull request merged**
