### PR TITLE
Snackbar fix

### PR DESCRIPTION
**Pull request by prateekbh**
This fixes num 8 on #263

### CODE REVIEW

**Comment by filoozom** [comment]
Test failed because of #273.

**Comment by prateekbh** [comment]
woops will fix

**Comment by filoozom** [comment]
Now both tests are failing. Strange, I do have the file:
```
$ file node_modules/@material/button/dist/mdc.button.css
node_modules/@material/button/dist/mdc.button.css: ASCII text, with very long lines
```

```node_modules/material-web-components/node_modules``` doesn't exist though.

**Comment by prateekbh** [comment]
yeah its going to be tricky... earlier if you installed `material-components-web` it'll install all packages of `@material` as dependency. And we picked everything from `@material`.

But now in 0.21.1 they seem to have changed this and some are installed as dev deps and some are not.

lemme talk to `mdc-web` team once and then fix this.

**Comment by filoozom** [comment]
Wonder if it might be linked to Travis caching. Does it work locally for you?

**Comment by prateekbh** [comment]
nups it breaks for me n local as well

**Comment by prateekbh** [comment]
yeah fixed.. phew...

**Pull request merged**
