### PR TITLE
[WIP] Add new components and props to documentation

### PR DESCRIPTION
**Pull request by filoozom**
Pretty much ready I think, just waiting for the new release and then I just need to update ```package.json```.

### CODE REVIEW

**Comment by cmonteiro128** [comment]
@prateekbh Can we get a new release?

**Comment by prateekbh** [comment]
@cmonteiro128 just published a new release

**Comment by prateekbh** [comment]
will merge this after sometime as it needs more changes

**Comment by filoozom** [comment]
Right, still had to add the latest changes to the ```Textfield``` component, but I'll make a new pull request.

**Pull request merged**
