### PR TITLE
TextField improvements

### PR DESCRIPTION
**Pull request by Cromefire**
- Added TextField outline
- Added outerStyle to style the outer element
- (Fixed prettier dependency)

### CODE REVIEW

**Comment by prateekbh** [comment]
Haven't reviewed the PR so far, but you are missing the update to `.d.ts` file

**Comment by Cromefire** [comment]
Sorry idea didn't show prettier errors in .d.ts files

**Comment by Cromefire** [comment]
Is it intended that prettier checks package-lock.json, which is automatically generated?

**Comment by prateekbh** [comment]
no it is not.. just by accident

**Comment by Cromefire** [comment]
I think the prettier config should be
`{,!(build|dist|out|package-lock.json)/**/}*.{js,_js,bones,es,es6,frag,gs,jake,jsb,jscad,jsfl,jsm,jss,mjs,njs,pac,sjs,ssjs,xsjs,xsjslib,jsx,ts,tsx,json,geojson,JSON-tmLanguage,topojson,json5,css,pcss,postcss,less,scss,graphql,gql,md,markdown,mdown,mdwn,mkd,mkdn,mkdown,ron,workbook,vue}`

**Comment by prateekbh** [comment]
actually just jsx, js should be file

**Comment by Cromefire** [comment]
just added `|package-lock.json` to your current config

**Comment by Cromefire** [comment]
It would be good, if you add this then all checks should be passed

**Comment by prateekbh** [comment]
Another question: Is there a strong reasong for `outerStyles` and not being able to do it with css and `className`?

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/6be6df368b5427dd2b13762f09e9cf64/raw/07e193a04d963e82e1487d36b91525387a00be0c/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [399676472](https://travis-ci.org/prateekbh/preact-material-components/builds/399676472), for commit [cc47646](https://github.com/prateekbh/preact-material-components/pull/853/commits/cc476466ebffc7c985b271678f1b3b78814d0d49).

**Comment by Cromefire** [comment]
`style`
results in:
```
<div>
    <input style="[...]">
</div>
```
because it is proxied

`outerStyles`
results in:
```
<div style="[...]">
    <input>
</div>
```
because is not proxied

className could work, but only with css classes in a `<style>` element so modifying it is difficult from javascript, because you would need to alter the <style> element

**Comment by Cromefire** [comment]
Travis has some problem with the chips, which are not modified by this pr

**Comment by Cromefire** [comment]
Maybe some problem with the things npm updated when I added prettier

**Comment by prateekbh** [comment]
nah its just a flake... i'll fix it...

**Comment by Cromefire** [comment]
I'll try to add some docs for outlined

**Comment by Cromefire** [comment]
I think you need to restart the first travis build, it had some (temporary I hope) problem with nvm

**Comment by Cromefire** [comment]
You should restart the whole build the second one tries to build node from source

**Comment by Cromefire** [comment]
@prateekbh please trigger a rebuild, both build have failed because nvm problems

**Comment by artipost** [comment]
Failed pictures (2): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/6df6dade914d92b4256019984bf0ed8f/raw/cb0db2a55bd255c2cead6c039c58a8e3440bcd26/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [399690892](https://travis-ci.org/prateekbh/preact-material-components/builds/399690892), for commit [3667a87](https://github.com/prateekbh/preact-material-components/pull/853/commits/3667a8764be65839c07dda24f248176feadbf62d).

**Comment by Cromefire** [comment]
Okay everything is working fine doc checking for TextField fails because I've edited it

prettier and chips are your turn

**Comment by artipost** [comment]
Failed pictures (2): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/246987753bfba8df0c3543fc746d9e9f/raw/c94f365be784b9c23c91c81fecde1ef62ad57ce6/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [399721945](https://travis-ci.org/prateekbh/preact-material-components/builds/399721945), for commit [d34b544](https://github.com/prateekbh/preact-material-components/pull/853/commits/d34b5442b0fa7241ee75094fcfe475622d2e05d2).

**Comment by Cromefire** [comment]
it's ready from my site

**Comment by prateekbh** [comment]
Sure, two more steps needed
a.) Bump the path version in package.json
b.) Download the two pics here: https://github.com/prateekbh/preact-material-components/pull/853#issuecomment-402262637 and replace them in `docs/tests/golden` folder.

I'll release the version ASAP

**Comment by Cromefire** [comment]
So I set the version from 1.4.6 to 1.4.7 right?

**Comment by prateekbh** [comment]
published

**Comment by Cromefire** [comment]
Thanks!

**Pull request merged**
