### PR TITLE
upgrading top-app-bar

### LINKED ISSUE #1271: 2.0 - Update TopAppBar
This is a tracking issue for updating TopAppBar

**Scope:** TopAppBar

### PR DESCRIPTION
**Pull request by prateekbh**
fixes #1271

- confirms to #1293

### CODE REVIEW

**Comment by prateekbh** [comment]
ping @cromefire

**Comment by cromefire** [comment]
Sorry, was kind of ill the last days

**Comment by prateekbh** [comment]
oh sorry to bother you.. hope you feel better :)

**Comment by cromefire** [comment]
Nothing bad I just wasn't at my computer

**Pull request merged**
