### PR TITLE
Install artipost.io

### PR DESCRIPTION
**Pull request by filoozom**
Follow up to #628

### CODE REVIEW

**Comment by filoozom** [comment]
PrettierCI is complaining about a file I didn't even touch, and how are we supposed to make it work without `npm run prettier(:write)` or git hook?

**Comment by artipost** [comment]
Failed pictures: [failed-pictures.zip](https://gist.githubusercontent.com/artipost/a11838b1de9b76883f5389756ccc81d0/raw/16bc65c10ef9cd1254008f0b90d6910f9fcc71a6/failed-pictures.zip)

**Comment by prateekbh** [comment]
yeah i guess the git hook is still necessary as CIs doesn't auto-commit work for forks.

**Comment by developit** [comment]
this is so bloody neat

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/f8a227c27083fb73e6cbb36bdb55f679/raw/5035b732696f8ea1c6a28da5c5d8c48fe2819cdd/failed-pictures.zip)

**Comment by artipost** [comment]
Failed pictures (5): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/89d45411fdc01b493634e632311b6ac2/raw/923c192d90bb99ce289ce6b8da2fe8c9487e789f/failed-pictures.zip)

**Comment by prateekbh** [comment]
@filoozom thanks for this. Looks so amazing.
Also, sorry for the delay. I just have a small thing. Now since we want to test the docs against the current codebase everytime.

**Pull request merged**
