### PR TITLE
[WIP] Port gh-pages to preact-cli

### LINKED ISSUE #220: Fix gh-pages on IE 11
The documentation does not work on IE 11 because of a ```babel``` / ```webpack``` configuration issue.

Maybe we should move ```gh-pages``` to ```preact-cli```?

### PR DESCRIPTION
**Pull request by filoozom**
This should make ```gh-pages``` more easy to maintain because we wouldn't need to use ```webpack``` / ```babel``` etc anymore. It also aims to use technologies that might be more know to ```preact``` developers (```preact-cli``` and ```preact-router``` instead of ```routie```).

- [x] Have same functionality as currenctly (except it can't be published)
- [x] Replace ```PostCSS``` with ```Sass``` to make it compatible with ```preact-cli```
- [x] Clean old build code
- [x] Replace ```routie``` with ```preact-router``` (required for SSR support as far as I can tell)
- [x] Enable SSR for all pages
- [x] Rename all routes (components) to the same names as ```material-components-web```
- [x] Comment dependencies (makes code a little cleaner I think)
- [ ] Use CSS Modules (everything is ```:global``` for now)
- [ ] Publish gh-pages using ```preact build``` and deploy the ```build``` directory (how could this be done? new branch?)
- [ ] Lint code
- [ ] Provide custom ```template.html```

By the way, this also fixes #220.

### CODE REVIEW

**Comment by prateekbh** [comment]
just a not: @filoozom for cleaning old build code there's already a PR open... but my thought process is to keep single build command to generate everything in the bundle using webpack

**Comment by filoozom** [comment]
Right, but this is just for ```gh-pages```, it has nothing to do with #208. It's just that with ```preact-cli``` we don't need to use the old build process and can easily generate SSR bundles and things like that.
Or do you want to keep the current build process for ```gh-pages``` too? I think ```preact-cli``` makes this a lot easier.

**Comment by filoozom** [comment]
@prateekbh Do you think we could put the docs source in ```master``` and add a build script that deploys the ```build``` directory to ```gh-pages```? Don't see how I could do it differently with ```preact-cli``` and the SSR build. Or maybe put the source in a ```docs``` branch.

**Comment by prateekbh** [comment]
a docs folder with a command to publish it to `gh-pages` sounds ace 👍

**Comment by filoozom** [comment]
Just to be clear, a ```docs``` folder on master or a ```docs``` branch?

**Comment by prateekbh** [comment]
a docs folder on master

**Comment by filoozom** [comment]
Guess I'll need to open a new pull request with ```master``` as base branch then, or do you know a way to keep these commits and "rebase" from ```master```?

**Comment by prateekbh** [comment]
@filoozom we can do one more thing, lets put this on docs branch and publish them on surge.sh?
that should make our lives a tad bit easier..
wht say?

**Comment by filoozom** [comment]
Sure, but pushing to ```gh-pages``` should be fairly easy too I think. Guess we'd just need to nuke the current branch and then:
```bash
$ git subtree push --prefix build origin gh-pages
```

Haven't tested it yet though.

I'm just going to open a new pull request for now based on ```master``` because rebasing all this from ```gh-pages``` to ```master``` seems to be an unnecessary headache.

**Comment by filoozom** [comment]
Closed in favour of #246.

**Pull request closed without merging**
