### PR TITLE
Fixed value update for floating label

### PR DESCRIPTION
**Pull request by cromefire**
Updates mdc's value on value change

### CODE REVIEW

**Comment by cromefire** [comment]
I thought we fixed that already

**Comment by cromefire** [comment]
I thought so, but:

image

**Comment by cromefire** [comment]
How about publishing `1.5.3-beta1` first (in `beta` channel) and if there are no major bugs that we **have** to solve before `2.0` we just republish it as `1.5.3` a few days later.

**Comment by prateekbh** [comment]
I'd say publish 1.5.3 and then do 1.5.4/5/6 as bug fixes only

**Comment by cromefire** [comment]
Well yes same concept

**Comment by prateekbh** [comment]
yes but no beta because we dont have a lot of users that'd opt in

**Comment by cromefire** [comment]
I cannot publish it currently, so if you want to go ahead.

**Comment by cromefire** [comment]
So I have access to my computer again, so I'll publish it now

**Comment by cromefire** [comment]
Published.

The branch for 2.0 is [`2.0`](https://github.com/prateekbh/preact-material-components/tree/2.0)

**Comment by prateekbh** [comment]
Thank you @cromefire 🤗

**Pull request merged**
