### PR TITLE
Card: change prop 16-9 to sixteenByNine

### PR DESCRIPTION
**Pull request by aravindballa**
Fix for #749 

- [x] Updated docs
- [x] Prettier fix

### CODE REVIEW

**Comment by aravindballa** [comment]
Got you!

Can I add a check for `sixteenByNine` in `MaterialComponent.js:getClassName()` and replace it with `--16-9`? Or is there any other way so that we do it in the `Card` component itself?

**Comment by prateekbh** [comment]
Just implement the prop manually in the card class.
Check if this prop is true, add the className manually to the actual className string

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/20e15e16dc69b9fedb741a5a387579f1/raw/a60b47c95efa686bdd9874534febf1c8ce3d60d6/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [405231627](https://travis-ci.org/prateekbh/preact-material-components/builds/405231627), for commit [da5ada3](https://github.com/prateekbh/preact-material-components/pull/868/commits/da5ada3e342ef3e50aebb5f3f286ec22ac0bc5b6).

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/daaee4ab110d7fbf2bfa3a2d70b63926/raw/b2384652568fb20a0a4637766f32caf7c9e4a43d/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [406508637](https://travis-ci.org/prateekbh/preact-material-components/builds/406508637), for commit [2548d09](https://github.com/prateekbh/preact-material-components/pull/868/commits/2548d09b7fe4ca713bd8b3b8e0eefcfa341a497c).

**Pull request merged**
