### PR TITLE
Make the two card demos look different

### PR DESCRIPTION
**Pull request by dandv**
Thought I had another instance of #869 but looking at the code, I saw the difference in the second action area being full-bleed.

Also fixed a run-on sentence.

### CODE REVIEW

**Comment by prateekbh** [comment]
@filoozom, we dont have the screenshot posted here by artipost, can you take a look

**Comment by filoozom** [comment]
@prateekbh Give me one second 🙂

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/3b3a0b7d3a277ccbe3d6b253816c3af6/raw/34fe7fa575cdb7c03f73335b5960ab15f1cbd310/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [406110932](https://travis-ci.org/prateekbh/preact-material-components/builds/406110932), for commit [ce95b40](https://github.com/prateekbh/preact-material-components/pull/870/commits/ce95b40d14e7a1378f5e4d796447cdac6e83e5df).

**Comment by prateekbh** [comment]
@dandv you'll just need to download the new screenshot and replace it in `docs/test/golden/wide/components`

**Comment by artipost** [comment]
Failed pictures (2): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/1d9f32b440878e1756a384839c5b131e/raw/551335435acb262b4f7241bd8239b7ecce1a6a03/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [408121991](https://travis-ci.org/prateekbh/preact-material-components/builds/408121991), for commit [c9b2026](https://github.com/prateekbh/preact-material-components/pull/870/commits/c9b2026e2ff775844745217251d43fac1922586f).

**Pull request merged**
