### PR TITLE
updating deps

### PR DESCRIPTION
**Pull request by prateekbh**

### CODE REVIEW

**Comment by YePpHa** [comment]
See [v0.30.0/CHANGELOG.md](https://github.com/material-components/material-components-web/blob/v0.30.0/CHANGELOG.md) for the breaking changes.

I've checked what should be changed and listed them here (I might've missed something):

__Select__
- Remove the `basic` prop as the css version of `mdc-select` element has been removed.
- Replace `mdc-simple-menu` with `mdc-menu`.
- Replace `mdc-simple-menu__items` with `mdc-menu__items`.

__Menu__
- Change the value of componentName to `menu`.
- Change all references of `MDCSimpleMenu` to `MDCMenu`.
- Change `MDCSimpleMenu:selected` to `MDCMenu:selected`.
- Change `MDCSimpleMenu:cancel` to `MDCMenu:cancel`.
- Replace `mdc-simple-menu` with `mdc-menu`.
- Replace `mdc-simple-menu__items` with `mdc-menu__items`.

__Checkbox__
- Replace `mdc-checkbox__checkmark__path` with `mdc-checkbox__checkmark-path`.

**Comment by mellogarrett** [comment]
Nice, have those changes been implemented in `preact-material-components` yet?

**Comment by YePpHa** [comment]
@mellogarrett not yet, however, I will probably do the changes when I get home today.

**Comment by prateekbh** [comment]
ummm guys this PR is just to close the 30 open PRs.. the actual changes will be in subsequent PRs

**Comment by YePpHa** [comment]
Okay, that's fine I will go and make the required PR's then

**Comment by prateekbh** [comment]
@YePpHa can you make a project instead so that just in case if anyone wants to pick in parallel you guys wont overlap

**Pull request merged**
