### PR TITLE
Replaced autobind-decorator with bind-decorator

### PR DESCRIPTION
**Pull request by cromefire**
For smaller bundles

### CODE REVIEW

**Comment by prateekbh** [comment]
This one throws better error messages, already we know there's an ear now.

**Comment by prateekbh** [comment]
Can you please take a look at the errors

**Comment by prateekbh** [comment]
Also why does `materialDom` even needs this???
I thought only event listeners will need this

**Comment by cromefire** [comment]
> Can you please take a look at the errors

It's a OSX/fsevents error, it seems that they have a broken/at least not prebuild version

**Comment by prateekbh** [comment]
Nups, I am taking about this
https://travis-ci.org/prateekbh/preact-material-components/jobs/424755513#L456

**Comment by cromefire** [comment]
> Also why does materialDom even needs this???
I thought only event listeners will need this

I could swear I had problems with that, but now it seems to work

**Comment by cromefire** [comment]
> Nups, I am taking about this
https://travis-ci.org/prateekbh/preact-material-components/jobs/424755513#L456

I think you can't override methods annotated with`@bind`.

**Pull request merged**
