### PR TITLE
Enforce code style

### LINKED ISSUE #243: Enforce code style
We should enforce a given code style and improve linting for the source code. For now, a lot of PRs contain lines that don't change in the slightest except their formatting, which makes it more difficult to track changes and review pull requests.

Also, I think that the current code doesn't respect all ```eslint``` rules. At least VS Code shows errors, I'll have to check if they're indeed from our eslint config.

### PR DESCRIPTION
**Pull request by filoozom**
This does following things:
- Sync ```eslint``` and ```prettier``` configs. This means that linting won't show errors for code fixed by ```prettier```.
- Make ```prettier``` mandatory, else travis builds will fail (added to ```test``` script)
- Run ```prettier``` on all files

Closes #243.

### CODE REVIEW

**Comment by prateekbh** [comment]
just curious, should we enforce single quotes? looks prettier :p

**Comment by filoozom** [comment]
I usually do, but this project contains a lot of double quotes so I didn't. Will gladly add it though 👍.
Damn, that was a real quick review... 😛

**Comment by prateekbh** [comment]
Lol I get notifications for evverything

**Comment by filoozom** [comment]
Actually ```prettier``` prefers double quotes, and we should use them for JSX, so maybe we should keep it like that.

**Comment by prateekbh** [comment]
cool makes sense

**Comment by filoozom** [comment]
Guess there's no need to publish a new version for this as it actually doesn't change anything except for contributors, so I can just go ahead and merge this, right?

**Comment by prateekbh** [comment]
yep

**Pull request merged**
