### PR TITLE
Fix LayoutGrid sample code

### PR DESCRIPTION
**Pull request by filoozom**
Adds the ```LayoutGrid.Inner``` component to the sample code.

(My bad, added a fix for the ```Card``` sample code in the same branch instead of create a new one)

### CODE REVIEW

**Comment by prateekbh** [comment]
is `package-lock.js` really needed? I am unaware of the usage of this

**Comment by filoozom** [comment]
It's not, just forgot to unstage the file created by ```npm``` since version 5 automatically. Deleted it!

**Comment by prateekbh** [comment]
can you put a snapshot of whats the change?
I cant really figure out

**Comment by filoozom** [comment]
Sorry, not quite sure what you're asking. You mean for the ```Card``` or the ```LayoutGrid``` sample code fix?

**Comment by prateekbh** [comment]
what changes on the page appearance?

**Comment by filoozom** [comment]
In the documentation of the ```LayoutGrid``` component, ```LayoutGrid.Inner``` was missing from the components list and wasn't used in the sample code. Without ```LayoutGrid.Inner```, the grid doesn't work (every cell is on its own line and doesn't respect the defined ```cols```).

I just added ```LayoutGrid.Inner``` to the components list and in the sample code as a parent from de ```LayoutGrid.Cell``` components.

**Pull request merged**
