### PR TITLE
Fix Tabs within TabBarScroller initialized multiple times

### LINKED ISSUE #795: Tabs within TabBarScroller are initialized multiple times
I found an issue with `Tabs` within a `Tabs.TabBarScroller`. Here is a simple example to reproduce the issue (this can also be reproduced on the [Tabs Scroller example](https://material.preactjs.com/component/tabs)) :
```jsx
<Tabs.TabBarScroller>
	<Tabs scroller>
		<Tabs.Tab>1</Tabs.Tab>
		<Tabs.Tab>2</Tabs.Tab>
		<Tabs.Tab>3</Tabs.Tab>
	</Tabs>
</Tabs.TabBarScroller>
```

### Details
When `Tabs` are used within a `Tabs.TabBarScroller`, this causes `MDCTabBar` to be constructed multiple times :
- Once in the [`MDCTabBarScroller.initialize`](https://github.com/material-components/material-components-web/blob/d9d695a5c6739e73ebcffcd0eb28ce8cd1c0e8d2/packages/mdc-tabs/tab-bar-scroller/index.js#L34) method
- Once in the [`Tabs.componentDidMount`](https://github.com/prateekbh/preact-material-components/blob/ac8a8556d4bb95d08650182be2520f00c1c17083/Tabs/Tabs.jsx#L31) method

This also causes `MDCTab` to be constructed multiple times as they are initialized in the [`MDCTabBar.initialize`](https://github.com/material-components/material-components-web/blob/d9d695a5c6739e73ebcffcd0eb28ce8cd1c0e8d2/packages/mdc-tabs/tab-bar/index.js#L50) method.

As `MDCTab` are created multiple times, the following error occurs when switching tab :
```Invalid tab component given as activeTab: Tab not found within this component's tab list```
These errors can be seen in the console on the [Tabs Scroller example](https://material.preactjs.com/component/tabs).

### Potential fixes
I haven't found a clean fix for now. We might want to condition `MDCTabBar` initialization on `scroller` property but we still need to access `MDCTabBar` instance to make `activeTabIndex` work :

```js
componentDidMount() {
	if (!this.props.scroller) {
		this.MDComponent = new MDCTabBar(this.control);
	}
	// This will break if `props.activeTabIndex` is set
	setActiveTabIndex(defaultProps, this.props, this.MDComponent);
}
```

Another idea would be to merge `Tabs` and `Tabs.TabBarScroller` components in a single component :

```jsx
// would only render tab-bar
<Tabs activeTabIndex={1}>
	<Tabs.Tab>1</Tabs.Tab>
	<Tabs.Tab>2</Tabs.Tab>
	<Tabs.Tab>3</Tabs.Tab>
</Tabs>

// would render tab-bar wrapped in a tab-bar-scroller
<Tabs activeTabIndex={1} scroller>
	<Tabs.Tab>1</Tabs.Tab>
	<Tabs.Tab>2</Tabs.Tab>
	<Tabs.Tab>3</Tabs.Tab>
</Tabs>
```

This allow us to access `MDCTabBar` instance to handle `activeTabIndex` changes and might make more sense (`scroller` property makes little sense if `Tabs` are not wrapped in a `TabBarScroller`).

Let me know what you think.

### PR DESCRIPTION
**Pull request by Dramloc**
This PR fixes #795. It also cleans up `Tabs` implementation not up to date with `@material/mdc-tab`.

This PR adds `TabBarScrollerTabs` component.  This component should be used within `TabBarScroller` instead of `Tabs`:
```jsx
<Tabs.TabBarScroller>
	<Tabs.TabBarScrollerTabs> { /* Instead of <Tabs scroller> */ }
		<Tabs.Tab>1</Tabs.Tab>
		<Tabs.Tab>2</Tabs.Tab>
		<Tabs.Tab>3</Tabs.Tab>
	</Tabs.TabBarScrollerTabs>
</Tabs.TabBarScroller>
```

`TabBarScrollerTabs` is similar to `Tabs` but does not perform `MDCTabBar` initialization, thus fixing the issue.

The other difference is that it does not accept `activeTabIndex`. Instead, `activeTabIndex` should be placed on `TabBarScroller` component:

```jsx
<Tabs.TabBarScroller activeTabIndex={1}>
	<Tabs.TabBarScrollerTabs>
		<Tabs.Tab>1</Tabs.Tab>
		<Tabs.Tab>2</Tabs.Tab>
		<Tabs.Tab>3</Tabs.Tab>
	</Tabs.TabBarScrollerTabs>
</Tabs.TabBarScroller>
```

Non-scrollable `Tabs` usage stays the same as before:
```jsx
<Tabs activeTabIndex={1}>
	<Tabs.Tab>1</Tabs.Tab>
	<Tabs.Tab>2</Tabs.Tab>
	<Tabs.Tab>3</Tabs.Tab>
</Tabs>
```

The component name is inspired by the class used by `@material/mdc-tab`: `.mdc-tab-bar-scroller__scroll-frame__tabs`.
**It might not be the best naming and this is still open to discussion.**

The PR also cleans up `Tabs` implementation by removing the unused `indicator-accent` property (material-components/material-components-web#1965) and adds `activeTabIndex` to Typescript declaration.

### CODE REVIEW

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/1e6daf2a97b57d4bbc26068714af0ab3/raw/311d79fb81199d8a43acc045b93287632fa8e6e7/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [379932454](https://travis-ci.org/prateekbh/preact-material-components/builds/379932454), for commit [8a69f05](https://github.com/prateekbh/preact-material-components/pull/796/commits/8a69f05856c9ada409c6d57904ca50781399284e).

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/0cb307bd304add1850872324d953ea73/raw/060b13686e5f8f8dab6e2b68950cf1ff9f8d212e/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [379933211](https://travis-ci.org/prateekbh/preact-material-components/builds/379933211), for commit [f41571e](https://github.com/prateekbh/preact-material-components/pull/796/commits/f41571eb07bd0a2a71e6be210089bc26e2917ef7).

**Comment by prateekbh** [comment]
@Dramloc don't bother about prettier i'll commit a fix at the end with this PR

**Comment by Dramloc** [comment]
@prateekbh ok thanks (I guess I will also leave reference screenshot as it is for now)

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/c568f292091c54dbd621f12b98c04f62/raw/e24d6ccd8a08312d288ac89903e24c2286bb092e/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [380280375](https://travis-ci.org/prateekbh/preact-material-components/builds/380280375), for commit [ef66922](https://github.com/prateekbh/preact-material-components/pull/796/commits/ef66922c5a6ceb9e92b47efb755c87744bc83780).

**Comment by Dramloc** [comment]
That was also my original thought (as proposed in the issue) but I found this solution a bit too opinionated:

- mdc-web defines `tab-bar` and `tab-bar-scroller` as two separate components
- if some properties are added to the scroller, it will be harder to implement
- I don't really know where user-defined classes and props should be added: the wrapper? the tab bar? both?

I've pushed this WIP implementation [here](https://github.com/Dramloc/preact-material-components/tree/experimental/scroller-tabs) if you want to compare the two.

**Comment by prateekbh** [comment]
So sorry for all the delay. LGTM.

Also you just need to download and replace the image in the folder

**Pull request merged**
