### PR TITLE
Added babel runtime as runtime dependecy

### PR DESCRIPTION
**Pull request by cromefire**
As babel is imported at runtime it needs to be present at runtime.

### CODE REVIEW

**Comment by artipost** [comment]
Failed pictures (27): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/99527eb8b70b03bebc950f31e762f9dc/raw/2f1ee192eb583278067c9c3dc7544ef2561fc0a3/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [413509784](https://travis-ci.org/prateekbh/preact-material-components/builds/413509784), for commit [ab388ae](https://github.com/prateekbh/preact-material-components/pull/922/commits/ab388ae8944b188ae71b12df960bba9f2d844a2b).

**Comment by prateekbh** [comment]
what happens to people using babel 6?

**Comment by cromefire** [comment]
Our code uses babel 7, their code uses babel 6 and they don't save that much space It's simply same as before runtime. It's just a bit better overall and even better if they also use babel 7 and runtime.

**Comment by cromefire** [comment]
For 6 it's `babel-runtime`, for 7 it's `@babel/runtime` and in addition `npm`/`yarn` should handle it appropriately

**Comment by cromefire** [comment]
No that's unnecessary because our code only uses Babel 7, what our code and their code uses is totally separated.

**Comment by cromefire** [comment]
If they import `babel-runtime` (aka. babel 6 + runtime), fine.
If they import none of them, fine.
If they import `@babel/runtime` (aka. babel 7 + runtime), it gets only shipped once, resulting in lower bundle size, still fine.

**Comment by prateekbh** [comment]
so what happens if they use babel 6 and try to use our components?
they get error?

**Comment by cromefire** [comment]
No the final bundle will include both, `babel-runtime` (if they use runtime) and `@babel/runtime`

**Comment by cromefire** [comment]
They just don't get bundles as small as babel 7 + runtime (same for babel 6 and 7 without runtime)

**Comment by cromefire** [comment]
As this is a serious bug, I think it should be released relatively soon

**Pull request merged**
