### PR TITLE
Add dark theme class to the toolbar

### PR DESCRIPTION
**Pull request by plusCubed**
Old:
untitled

New:
untitled2

This makes the switch more visible. (cont. from #199)

### CODE REVIEW

**Comment by prateekbh** [comment]
A less bright white switch is more visible than the the older more whiter one????

**Comment by plusCubed** [comment]
Mostly the right side which blends in, on the old one it looks more like just a white circle.

**Comment by prateekbh** [comment]
@plusCubed can you send the screenshot of the entire page?

**Comment by plusCubed** [comment]
Old:
prateekbh github io-preact-material-components-

New:

**Comment by plusCubed** [comment]
The new one is designed to be used on dark backgrounds by MDC.

**Pull request merged**
