### PR TITLE
Proper refs for TextField and ref typing

### PR DESCRIPTION
**Pull request by cromefire**
- [x] `TextField` refs can properly access `TextFieldInput`
- [x] All Elements that are wrappers around an `<input>` element allow access to a reference of that input element
- [ ] Type all refs

A ref of `TextFieldInput` can be accessed via
``` typescript
text_field_ref.tfInput
```

Input refs will be accessible via
``` typescript
ref.input
```

### CODE REVIEW

**Comment by prateekbh** [comment]
What's are we trying to achieve with this?

**Comment by prateekbh** [comment]
> All Elements that are wrappers around an <input> element allow access to a reference of that input element

I would discourage this. The underlying Dom is not for us to own. A `ref` to this would make a breaking change for us even though mdc APIs remain same

**Comment by cromefire** [comment]
> A `ref` to this would make a breaking change for us even though mdc APIs remain same

Where do you see a breaking change?

> The underlying Dom is not for us to own

Is't pure preact

> What's are we trying to achieve with this?

Currently the only way to access the input element (see #702, e.g. for calling DOM methods on it) is either to use `MDComponent._input` (what's definitely discouraged) or traversing the DOM your self (using `document.getElementById()` etc.; that's also discouraged, because as you said, the DOM is not owned by us).

**Comment by cromefire** [comment]
Example for a DOM API not supported by MDCComponents: `reportValidity()`

**Comment by prateekbh** [comment]
> Where do you see a breaking change?

E.g. Select was never implemented using the <select> component until recently, if someday they go back it won't be a breaking change for them as the APIs will be same but it will be for us as we won't have a Dom to give ref to.

Therefore I would suggest to own only mdc properties and not have any additional logic on us.

Plus a Dom ref to top level always exposes inner Dom to work with.

**Comment by cromefire** [comment]
Traversing through the inner Dom is really manual, there are use cases that **need** that Dom ref, so the alternative is to tell the users to use some hacks to that will also have that breaking changes and are not designed to be used like this. That means that this would be a breaking change from MWC which we cannot influence any ways.
Maybe would do better to implement that and then mark it as "Only use it, if you really need"

**Comment by prateekbh** [comment]
> Maybe would do better to implement that and then mark it as "Only use it, if you really need"

I've had some discussion to add some kind of "experimental"  features to this package always. Just never had enough time to do so.

Do u have a good API design to do so?

**Comment by cromefire** [comment]
> Do u have a good API design to do so?

The only thing I can think of right now is annotating it in the docs and annotating it in the source.

**Comment by cromefire** [comment]
Dopping this in favor of the refactor for `2.0`

**Comment by cromefire** [comment]
Please leave the branch for now

**Pull request closed without merging**
