### PR TITLE
[Select] Add name prop

### LINKED ISSUE #1279: Select component Name and ID
I am trying to mention name on select component. But the name doesnt appear in the html. This is same for ID as well. Is this by design ? Is there a way to display error message for select ? Like Textfield has a valid option. The mdc does has a valid option. 

https://material.io/develop/web/components/input-controls/select-menus/

### PR DESCRIPTION
**Pull request by cromefire**
Fixes #1279

### CODE REVIEW

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/bc48fed04cd02aadd1ee2ae2468f1f89/raw/140dcbee4590254aef36a98addc87e7d7c3e511f/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [494500557](https://travis-ci.org/prateekbh/preact-material-components/builds/494500557), for commit [cf7bb95](https://github.com/prateekbh/preact-material-components/pull/1281/commits/cf7bb95bcf21b1acf51f00490f1f260b1efeb809).

**Comment by cromefire** [comment]
@prateekbh review and merge please

**Comment by prateekbh** [comment]
For #1279 we should take those props (and form related props) and put it on control ourselves.

That makes it much more stable API. Expecting people to send them in control props might be a bit unintuitive

**Comment by cromefire** [comment]
Well it's a hot fix for 1.x I didn't want to look up all the properties

**Comment by prateekbh** [comment]
then lets just do it for name right now?

**Comment by cromefire** [comment]
Sure change it, I'm currently quite busy

**Comment by prateekbh** [comment]
Will do 🙂

**Comment by artipost** [comment]
Failed pictures (1): [failed-pictures.zip](https://gist.githubusercontent.com/artipost/28524983b1253f0c0c1eadf0459cc4f5/raw/e9115bb0cf977f402b77b3f257a49f0a39a87461/failed-pictures.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [495850214](https://travis-ci.org/prateekbh/preact-material-components/builds/495850214), for commit [327ddb5](https://github.com/prateekbh/preact-material-components/pull/1281/commits/327ddb5354e5887b7a984603126ca0c74ccaf1dd).

**Comment by cromefire** [comment]
There are some prettier errors somehow (I don't know why, it should be auto fixed...

Also npm made that babel security updates, can you please synchronize the versions among them again?

**Comment by prateekbh** [comment]
sure will fix... can you LG for the code till then?

**Comment by cromefire** [comment]
Everything fine, but I can't approve, because it my PR you have to approve it

**Comment by cromefire** [comment]
Can you publish please?

**Comment by prateekbh** [comment]
Will do today

**Comment by prateekbh** [comment]
done 1.5.7

**Comment by cromefire** [comment]
https://isitmaintained.com/project/prateekbh/preact-material-components

**Comment by prateekbh** [comment]
OMG... No 🙈.. we're only two maintainers, it's not our day job.. we try our best to keep stuff stable.
I guess we should draw a line here

It'll be extremely difficult for us to get that green 😐

WDYT?

**Comment by cromefire** [comment]
I think 8 Days is a very good time, I think that should deserve green, but I just found it and wanted to share it

**Comment by cromefire** [comment]
I guess that's not a really good indication.
And we're even better than mwc: https://isitmaintained.com/project/material-components/material-components-web

**Comment by cromefire** [comment]
If you search around all the bigger projects are slower

**Pull request merged**
