### PR TITLE
fix: set labelRef

### PR DESCRIPTION
**Pull request by TroyTae**
There is no setter of labelRef.
So labelRef is always `undefined`, and cannot executive this code:
```
protected updateSelection() {
      ...

      const selectedIndex = this.MDComponent.selectedIndex;
      if (selectedIndex === 0) {
        if (this.labelRef) {
          this.labelRef.classList.remove('mdc-floating-label--float-above');
        }
      } else {
        if (this.labelRef) {
          this.labelRef.classList.add('mdc-floating-label--float-above');
        }
      }
    }
  }
```
So I fix it!

before:
image

after:
image

### CODE REVIEW

**Comment by TroyTae** [comment]
@cromefire @prateekbh 
After create this PR, I tried to find more error in docs.
I cannot find more strange UI, but still errors exist in CI.
When I contribute to material-components-web, maintainer told me:
"When UI is changed, maintainer needs to update golden.json(screenshot test data). It's similar with snapshot test."
Is this same kind of happen..?

**Comment by cromefire** [comment]
No not anymore someone of us has to approve the changes online

**Comment by TroyTae** [comment]
Then... how can I figure out about the errors?
I cannot confirm the screenshot image in cypress.

**Comment by cromefire** [comment]
That's nothing you can do it's just that we haven't approved it

**Comment by TroyTae** [comment]
@cromefire 
Oh really?
After I saw this [comment](https://github.com/prateekbh/preact-material-components/issues/1343#issuecomment-568535866), I guess `blockers` is test error.
Then I will wait for your approval :)

**Comment by prateekbh** [comment]
I can understand it's extremely irritating when tests does not match the actual screen.
I'll take a look at this today

**Comment by prateekbh** [comment]
Ahh my bad. @TroyTae you need these changes in branch `2.0` not `2.0 for preact X`

Can you just send the intended changes from a new branches?

Those should work seamless

**Comment by TroyTae** [comment]
@prateekbh 
Sure!
Is it better to move my previous PR?
These two PR(#1345, #1346) also merged to `2.0 for preact X`.

**Comment by prateekbh** [comment]
Oh no. Yes they must all be going to `2.0`

**Comment by prateekbh** [comment]
Sorry this is completely on me.

**Comment by TroyTae** [comment]
@prateekbh 
I sent same three PR to `2.0`.
After weekend, please delete my commit(git reset hard & force push) in `2.0 for preact X`.
Thank you :)

**Pull request closed without merging**
