### PR TITLE
temporary fix for minified code example

### PR DESCRIPTION
**Pull request by prateekbh**
temporary fix for minified code in docs

### CODE REVIEW

**Comment by filoozom** [comment]
You could do something like:
```
const jsxToString = jsx => require('jsxToString')(jsx, {
    displayName: 'Button'
})
```
I think.

**Comment by prateekbh** [comment]
not sure though how, a complex nested elements like <Select> will work with this

**Comment by filoozom** [comment]
Right. Strange that it worked on your local version.

**Comment by prateekbh** [comment]
nah i was using `preact-watch`. broke for me too with `preact serve`

**Pull request merged**
