### PR TITLE
adding fab2.0

### LINKED ISSUE #1253: 2.0 - Update Fab
This is a tracking issue for updating Fab

**Scope:** Fab

### PR DESCRIPTION
**Pull request by prateekbh**
Fixes #1253 
- updated fab2.0
- updated docs
- reverted component names for card(realized this'll help us and devs have less renames)

### CODE REVIEW

**Comment by cromefire** [comment]
@prateekbh A few things for applitools:

1) Please add Firefox, it's still very wide used
2) Please set the Desktop resolution to 1920x1080, because that's most common today
3) Please set the IPhone to safari, because chrome already included

**Comment by prateekbh** [comment]
@cromefire all good but about pt 3
all browsers are anyways safari on iphone so how does it matter

**Comment by cromefire** [comment]
Well I don't know what that "Chrome emulation" means then, what does it do?

**Comment by prateekbh** [comment]
Screen Shot 2019-03-14 at 12 16 46 AM

@cromefire Applitools say browser to be safari 11, i guess we're good here.

**Comment by prateekbh** [comment]
Will add Firefox in upcoming PRs

**Pull request merged**
